version: "3" 
services:
  web_jenkins3:
    image: alexrogna/jenkins3_web:prod
    expose:
      - 3000
    env_file:
      - .env/production/database_jenkins3
      - .env/production/web_jenkins3
    environment:
      - VIRTUAL_HOST=jenkins3.alexrogna.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=jenkins3.alexrogna.com
    networks:
      - proxy
    restart: always

  database_jenkins3:
    image: postgres
    env_file:
      - .env/production/database_jenkins3
    volumes:
      - db_data_jenkins3:/var/lib/postgresql/data
    networks:
      - proxy
    restart: always
    
  db-migrator_jenkins3:
    image: alexrogna/jenkins3_web:prod
    command: ["./wait-for", "--timeout=300", "database_jenkins3:5432", "--", "bin/rails", "db:create" , "db:migrate"]
    env_file:
      - .env/production/database_jenkins3
      - .env/production/web_jenkins3
volumes:
  db_data_jenkins3:
networks:
  proxy: