version: "3"
services:
  web_jenkins3:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "3031:3000"
    volumes: 
      - ./jenkins3:/opt/app
      - gem_cache_jenkins3:/gems
    env_file: 
      - .env/development/database_jenkins3
      - .env/development/web_jenkins3
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_jenkins3
    networks:
      - network
  webpack_dev_server_jenkins3:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "3065:3065"
    volumes: 
      - ./jenkins3:/opt/app
      - gem_cache_jenkins3:/gems
    env_file: 
      - .env/development/database_jenkins3
      - .env/development/web_jenkins3
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    networks:
      - network
  database_jenkins3:
    image: postgres
    env_file: 
      - .env/development/database_jenkins3
    volumes: 
      - db_data_jenkins3:/var/lib/postgresql/data
    networks:
      - network
volumes: 
  db_data_jenkins3:
  gem_cache_jenkins3:
networks:
  network: